#!/bin/bash
# Daily Brief Script for Tellus (Restaurant GM Agent)
# Generates a morning briefing based on compiled memory

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE="/home/zemi/clawd"
MEMORY_DIR="${WORKSPACE}/memory"

TODAY=$(date +%Y-%m-%d)
TOMORROW=$(date -d "tomorrow" +%Y-%m-%d)
BRIEF_FILE="${SCRIPT_DIR}/brief-${TODAY}.md"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

log "=== Generating Daily Brief for ${TODAY} ==="

# Check for pre-written brief from yesterday's review
PREV_BRIEF="${SCRIPT_DIR}/brief-${TODAY}.md"
if [ -f "${PREV_BRIEF}" ]; then
    log "Found pre-written brief for ${TODAY}"
    cat "${PREV_BRIEF}"
    exit 0
fi

# Build context from memory
MEMORY_CONTENT=""
if [ -f "${WORKSPACE}/MEMORY.md" ]; then
    MEMORY_CONTENT=$(cat "${WORKSPACE}/MEMORY.md}")
fi

# Check today's notes if already exist
TODAY_NOTES=""
if [ -f "${MEMORY_DIR}/${TODAY}.md" ]; then
    TODAY_NOTES=$(cat "${MEMORY_DIR}/${TODAY}.md")
fi

# Check for pending items from previous days
PENDING_ITEMS=$(find "${MEMORY_DIR}" -name "*.md" -newer "${WORKSPACE}/MEMORY.md" -type f 2>/dev/null | head -5)

# Generate brief using agent if available
PROMPT="Generate a morning briefing for Tellus (restaurant GM) for ${TODAY}.

## Context

### Long-term Memory:
${MEMORY_CONTENT:0:2000}

### Today's Existing Notes:
${TODAY_NOTES:-None}

### Today's Date: ${TODAY}
### Day of Week: $(date '+%A')

## Task
Create a concise morning briefing covering:

1. **Today's Focus** - Top 3 priorities based on memory and patterns
2. **Sales Targets** - Based on historical data if available
3. **Staffing Notes** - Any relevant staffing info from memory
4. **Prep Needs** - What should be prepared based on patterns
5. **Watch For** - Potential issues or busy periods
6. **Pending Items** - Any items flagged in previous notes

## Format
Use a concise briefing format with clear sections. Keep it actionable.

## Output
Write directly to ${BRIEF_FILE}

Do NOT modify configs. Focus on operational readiness."

log "Generating briefing..."

if command -v sessions_spawn &> /dev/null; then
    echo "${PROMPT}" | sessions_spawn --model mini --prompt "You are a restaurant GM agent generating morning briefing." 2>&1
elif [ -f "${WORKSPACE}/bin/sessions_spawn" ]; then
    echo "${PROMPT}" | "${WORKSPACE}/bin/sessions_spawn" --model mini 2>&1
else
    # Fallback: create basic brief
    cat > "${BRIEF_FILE}" << 'EOF'
# Daily Briefing - ${TODAY}

## Today's Focus
- Review yesterday's performance metrics
- Check vendor deliveries for the day
- Morning team check-in

## Key Reminders
- No critical items flagged in memory

## Upcoming
- Check tomorrow's briefing for detailed prep

---
*Generated by Tellus Daily Brief System*
EOF
    sed -i "s/\${TODAY}/${TODAY}/g" "${BRIEF_FILE}"
    log "Created basic briefing at ${BRIEF_FILE}"
fi

# Display the briefing
if [ -f "${BRIEF_FILE}" ]; then
    log "=== Briefing for ${TODAY} ==="
    cat "${BRIEF_FILE}"
else
    log "Warning: Briefing file not created"
fi

log "=== Brief Complete ==="
